version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: laravel-app
    container_name: backend
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=task-manager
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"   
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    image: vue-app
    container_name: frontend
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html  # Servir les fichiers frontend construits ici
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always  

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task-manager
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network
    restart: always  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network
    restart: always  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
